version: "1"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    depends_on:
      - postgres
    restart: always
    networks:
      - practice
    
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    networks:
      - practice

networks:
  practice: